config/routes.rb
Rails.application.routes.draw do
  resources :tests,
    path_names: {new: "tests", show: "profile"}
  get 'quiz/new'
  get 'users/new'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'show_leaderboard/:id' => 'leaderboards#show', as: 'show_leaderboard'
  get 'leaderboards' => 'leaderboards#index'

  root 'static_pages#home'
  get 'login' => 'sessions#login'
  post 'login' => 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get "/auth/:provider/callback" => 'sessions#oauth'
  resources :users,
    only: [:new, :create, :show, :edit, :update],
    path_names: {new: "signup", show: "profile"}
  resources :questions
  resources :options

  resources :tests, path_names: {new: "tests", show: "profile"}
  get 'current_test/:id' => 'tests#take', as: 'take_test'
  patch 'submit/:id' => 'tests#submit_test', as: 'submit'
  post 'submit_contact_form' => 'static_pages#submit_contact_form'
  get 'password_reset_form' => 'static_pages#password_reset_form'
  post 'reset_password' => 'sessions#reset_password'
end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  def index
    @tests = Test.all
  end

  def show
    @test = Test.find(params[:id])
    @users = User.have_taken_test(@test.id)
    @attempts = Attempt.where(test_id: @test.id)
  end
end

app/views/leaderboards/index.html.erb
<div class="page-header">
  <h1>Listing tests</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th>Test Name</th>
      <th></th>
    </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @tests) do |test| %>
        <td><%= test.name %></td>
        <td><%= link_to "Show Leaderboard", show_leaderboard_path(test) %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/leaderboards/show.html.erb
<div class="page-header">
  <h1>Leaderboard:</h1>
  <h2><%= @test.name %></h2>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th>First Name</th>
      <th>Last Initial</th>
      <th><%= link_to 'Aptitude', sort: 'score' %></th>
    </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @users) do |user| %>
        <td><%= user.first_name %></td>
        <td><%= user.last_name.first %></td>
        <td><%= @attempts.where(user_id: user.id).order(:score).last.score %></td>
      <% end %>
    </tr>
    </tbody>
  </table>

  <% if @users.empty? %>
    <h3>--- No users have taken this test ---</h3>
  <% end %>
</div>