config/routes.rb
Rails.application.routes.draw do
  resources :tests,
    path_names: {new: "tests", show: "profile"}
  get 'quiz/new'
  get 'users/new'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'show_leaderboard/:id' => 'leaderboards#show', as: 'show_leaderboard'
  get 'leaderboards' => 'leaderboards#index'

  root 'static_pages#home'
  get 'login' => 'sessions#login'
  post 'login' => 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get "/auth/:provider/callback" => 'sessions#oauth'
  resources :users,
    only: [:new, :create, :show, :edit, :update],
    path_names: {new: "signup", show: "profile"}
  resources :questions
  resources :options

  resources :tests, path_names: {new: "tests", show: "profile"}
  get 'current_test/:id' => 'tests#take', as: 'take_test'
  patch 'submit/:id' => 'tests#submit_test', as: 'submit'
  post 'submit_contact_form' => 'static_pages#submit_contact_form'
  get 'password_reset_form' => 'static_pages#password_reset_form'
  post 'reset_password' => 'sessions#reset_password'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <%= image_tag("logo.png", :alt => "logo") %>
      </a>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% is_current_page = current_page?(root_path) ? 'active' : '' %>
        <li class="<%= is_current_page %>">
          <%= link_to 'Home', root_path %>
        </li>
        <li class="<%= current_page?(about_path) ? 'active' : '' %>"><%= link_to 'About', about_path %></li>
        <li class="<%= current_page?(contact_path) ? 'active' : '' %>"><%= link_to 'Contact', contact_path %></li>
        <li class="<%= current_page?(leaderboards_path) ? 'active' : '' %>"><%= link_to 'Leaderboard', leaderboards_path %></li>
        <% if current_user %>
          <li class="<%= current_page?(tests_path) ? 'active' : '' %>"><%= link_to 'Tests', tests_path %></li>
        <% end %>
      </ul>
      <p class="navbar-text navbar-right">
        <% if current_user %>
          <%= link_to "Signed in as #{current_user.email}", edit_user_path(current_user) %>
          <%= link_to 'Logout', logout_path, method: :delete %>
        <% else %>
          <%= link_to 'Signup', new_user_path %>
          <%= link_to 'Login', login_path %>
        <% end %>
      </p>
    </div>
  </div>
</nav>
<div class="container">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <%= msg %>
    <% end %>
  <% end %>
  <%= render 'layouts/authentication' %>
  <%= yield %>
</div>
</body>
<div>
  <footer class="bs-docs-footer" role="contentinfo">
    <div class="container">
        <a href="https://www.linkedin.com/groups/5128205">LinkedIn Group |</a>
        <a href="https://twitter.com/sellingrank">Twitter |</a>
        <a href="../contact">Contact |</a>
        <a href="../about/">About</a>
      <p> Copyright © SellingRank 2016</p></div>
  </footer>
</div>
</html>